[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "suetes"
version = "0.8.1"
description = "Suetes is a Differentiable Regional Weather Model (JAX)"
dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
    "jax",
    "jaxlib",
    "xarray",
    "cartopy",
    "pandas",
    "optax",
    "cdsapi"
]

[tool.setuptools]
packages = ["suetes"]

[tool.pytest.ini_options]
testpaths = ["tests", "benchmarks"]
pythonpath = ["."]